services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit

    worker_1:
      image: worker_1
      build:
        context: ./
        dockerfile: ./worker_1_folder/Dockerfile
      networks:
      - rabbit

      
  consumer:
    image: 127.0.0.1:5000/consumer
    build: consumer/.
    networks:
      - rabbit
  producer:
    image: 127.0.0.1:5000/producer
    build: producer/.
    networks:
      - rabbit

networks:
  rabbit:
    driver: overlay
    attachable: true
